#!/usr/bin/env node
/**
 * NextUp Transit (v7) — production local dev server.
 *
 * This is the shipped app (promoted from the former `main-next/` on 2026-09-03;
 * the previous v6 app is retired at `../Main-v6/`). It is fully self-contained:
 * it carries its own data (routes-data.json, stations/) and talks to the
 * OneBusAway API directly from the browser (see lib/transit-api.js), so it needs
 * no server-side API — there are no /api or GTFS endpoints here and no parsers/.
 *
 * NOTE: route/stop data (routes-data.json, stations/) is regenerated by the v6
 * toolchain kept in ../Main-v6/ (parsers/ + scripts/ + route-config.html + its
 * /api server). To refresh the data, run that legacy app on a temp port, export,
 * and copy the JSON here. Nothing here depends on Main-v6 at runtime.
 *
 * Static files only. Usage: node server.js [port]   (default 8080)
 */
const http = require('http');
const fs = require('fs');
const path = require('path');

// More libuv file-I/O threads (default 4) so a few stuck OneDrive Files-On-Demand
// placeholder reads can't starve reads of files that ARE local.
process.env.UV_THREADPOOL_SIZE = process.env.UV_THREADPOOL_SIZE || '16';

const PORT = parseInt(process.argv[2] || '8080', 10);
const ROOT = __dirname;

const MIME = {
  '.html': 'text/html',
  '.js':   'application/javascript',
  '.css':  'text/css',
  '.json': 'application/json',
  '.png':  'image/png',
  '.svg':  'image/svg+xml',
  '.ico':  'image/x-icon',
  '.webmanifest': 'application/manifest+json',
};

// Bound every file op so an un-materialized OneDrive placeholder (whose read can
// hang indefinitely) fails THIS request fast instead of freezing the whole
// single-threaded server.
const READ_TIMEOUT_MS = 10000;
function _withTimeout(promise, ms, label) {
  let t;
  const timeout = new Promise((_, reject) => {
    t = setTimeout(() => reject(new Error(label || 'timeout')), ms);
  });
  return Promise.race([Promise.resolve(promise).finally(() => clearTimeout(t)), timeout]);
}

async function serveStatic(req, res) {
  let filePath = path.join(ROOT, req.url.split('?')[0]);
  if (filePath.endsWith('/')) filePath += 'index.html';

  if (!filePath.startsWith(ROOT)) {
    res.writeHead(403); res.end('Forbidden');
    return;
  }

  try {
    let stat = await _withTimeout(fs.promises.stat(filePath), READ_TIMEOUT_MS, 'stat timeout');
    if (stat.isDirectory()) filePath = path.join(filePath, 'index.html');
    const ext = path.extname(filePath).toLowerCase();
    const mime = MIME[ext] || 'application/octet-stream';
    const content = await _withTimeout(fs.promises.readFile(filePath), READ_TIMEOUT_MS, 'read timeout');
    res.writeHead(200, { 'Content-Type': mime, 'Access-Control-Allow-Origin': '*' });
    res.end(content);
  } catch (e) {
    if (/timeout/.test(e.message)) {
      console.warn(`[serveStatic] read timed out for ${req.url} — cloud placeholder not downloaded?`);
      res.writeHead(504, { 'Content-Type': 'text/plain' });
      res.end('File read timed out — is this a OneDrive placeholder that has not been downloaded locally?');
    } else {
      res.writeHead(404);
      res.end('Not found');
    }
  }
}

const server = http.createServer(async (req, res) => {
  await serveStatic(req, res);
});

server.listen(PORT, () => {
  console.log(`NextUp Transit (v7) running at http://localhost:${PORT}`);
  console.log(`  Static root: ${ROOT}`);
});
